export const CONTACT_SUBMISSION_REQUEST = 'CONTACT_SUBMISSION_REQUEST';
export const CONTACT_SUBMISSION_SUCCESS = 'CONTACT_SUBMISSION_SUCCESS';
export const CONTACT_SUBMISSION_FAIL = 'CONTACT_SUBMISSION_FAIL';
export const CONTACT_SUBMISSION_RESET = 'CONTACT_SUBMISSION_RESET';